---

- Media:
    - Request something:
        icon: jellyseerr.png
        href: http://odin.local:5055
        description: Jellyseerr

    - Watch something:
        icon: jellyfin.png
        href: http://odin.local:8096
        description: Jellyfin

    - Read something:
        icon: kavita.png
        href: http://odin.local:10888
        description: Kavita

    - Track it:
        icon: trakt.png
        href: https://trakt.tv
        description: trakt.tv

- Management:
    - Torrents:
        icon: qbittorrent.png
        href: http://odin.local:8080
        description: qBitTorrent

    - TV Shows Tracker:
        icon: sonarr.png
        href: http://odin.local:8989
        description: Sonarr

    - Movies Tracker:
        icon: radarr.png
        href: http://odin.local:7878
        description: Radarr

- Other:
    - Seq logs:
        icon: seq.png
        href: https://seq.typingrealm.com
        description: Logging system for pet projects

    - PgAdmin:
        icon: pgadmin.png
        href: https://pgadmin.typingrealm.com
        description: PostgreSQL browser for pet projects

    - Redis Insights:
        icon: redis.png
        href: http://odin.local:5540
        description: Redis browser for pet projects

    - Indexers setup:
        icon: prowlarr.png
        href: http://odin.local:9696
        description: Prowlarr
